### ISSUE TITLE
перезапись параметров

### ISSUE THREAD

**Issue by DimaDK24** [Sergej-Karyuhin/my-NeutronMail#3]
https://github.com/Sergej-Karyuhin/my-NeutronMail/blob/b5e9652338e87b6de5074e656df6ca451fbbac05/style.css#L131

```css
.buttonCreateAccount {
  width: 249px;
  height: 59px;
  border-radius: 28px;
  border: 0;
  background-color: #5f2966;
  color: #fff;
  cursor: pointer;

  font-family: 'Titillium Web', sans-serif;
  font-weight: 900;
  font-size: 16px;

  box-shadow: 0 7px 9px 0 rgba(100, 115, 151, .15), 0 13px 21px 0 rgba(20, 80, 204, .27), 0 13px 21px 0 rgba(0, 0, 0, .15),
  0 4px 16px 0 rgba(102, 145, 233, .33), 0 4px 16px 0 rgba(0, 0, 0, .09), 0 3px 9px 0 rgba(53, 103, 205, .09),
  0 3px 9px 0 rgba(0, 0, 0, .09), 0 3px 3px 0 rgba(102, 145, 233, .09), 0 3px 3px 0 rgba(0, 0, 0, .17);
  background-image: linear-gradient(to right, #5f2966 0%, #646c92 40%, #646c92 60%, #5f2966 100%);

  font-size: 18px;
  font-weight: 700;
  letter-spacing: 0.2px;
}
```

В этом селекторе дважды указаны font-weight и font-size. По центру и снизу. Первые перезаписываются вторыми и поэтому их можно спокойно убрать.
